# Generated by Django 5.2.1 on 2025-05-13 17:45

import django.db.models.deletion
import shortener.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='expires_at',
            field=models.DateTimeField(db_index=True, default=shortener.models.get_expiration_date),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.shorturl')),
            ],
        ),
    ]
